<br>
<div class="card">
    <img src="images/footer.png" class="card-img">
    <div class="card-img-overlay">
        <div class="row">
            <div class="col-lg-9"></div>
            <div class="col-lg-3">
                <div class="card bg-light mb-3" style="max-width: 50%">
                    <div class="card-body">
                        <p style="text-align: left; font-size: 10px">
                            <b>Olsker Cupcakes, Inc.</b>
                            <br>
                            1355 Lynby, 3. gade, 900
                            <br>
                            Danmark, CA 94103
                            <br>
                            Tlf.: (45) 43 56 34 23
                            <br>
                            <br>
                            <b>Vores email:</b>
                            <a href="#">olskercupcakes@gmail.com</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>